services:
  nginx:
    image: nginx:1.27-alpine
    ports: ["80:80"] #public HTTP port 
    volumes:
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
      - frontend
  stripe-tunnel:
    image: stripe/stripe-cli:latest
    entrypoint: >
      /bin/sh -c "stripe listen --forward-to backend:8000/api/payments/webhook --api-key $$(cat /run/secrets/stripe_secret_key | xargs)"
    depends_on:
      - backend
    secrets: 
      - stripe_secret_key

  backend:
    build: ./backend
    env_file: .env
    secrets : 
      - stripe_secret_key
      - stripe_webhook_secret
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - STRIPE_SECRET_KEY_FILE=/run/secrets/stripe_secret_key
      - STRIPE_WEBHOOK_SECRET_FILE=/run/secrets/stripe_webhook_secret
    volumes:
      - ./backend:/app
    command: python -m uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports: 
      - "8000:8000"
    expose: 
      - "8000" ##IMPORTANT THIS IS ONLY DURING DEVLOPMENT TO TEST ON LOCAL MACHINE, DELETE LINE LATER
    depends_on:
  
      db:
        condition: service_healthy
    
  frontend:
    build: 
      context: ./frontend
      target: dev 
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0 --port 5173
    expose: 
      - "5173" ##IMPORTANT THIS IS ONLY DURING DEVLOPMENT TO TEST ON LOCAL MACHINE, DELETE LINE LATER
    
  db:
    image: postgres:16-alpine
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 30

volumes:
  pgdata:

secrets:
  stripe_secret_key:
    file: ./secrets/stripe_secret_key.txt
  stripe_webhook_secret:
    file: ./secrets/stripe_webhook_secret.txt
  
