menu_items = [
  {
    "id": 1,
    "name": 'Grilled Chicken Bowl',
    "mealType": ['lunch', 'dinner'],
    "diets": ['gluten-free'],
    "category": 'entree',
    "diningHall": 'Hampshire',
  },
  {
    "id": 2,
    "name": 'Veggie Wrap',
    "mealType": ['lunch'],
    "diets": ['vegetarian'],
    "category": 'entree',
    "diningHall": 'Berkshire',
  },
  {
    "id": 3,
    "name": 'Tofu Rice Plate',
    "mealType": ['dinner'],
    "diets": ['vegan', 'gluten-free'],
    "category": 'entree',
    "diningHall": 'Franklin',
  },
  {
    "id": 4,
    "name": 'Egg Sandwich',
    "mealType": ['breakfast'],
    "diets": ['vegetarian'],
    "category": 'entree',
    "diningHall": 'Worcester',
  },
  {
    "id": 5,
    "name": 'Turkey Panini',
    "mealType": ['lunch'],
    "diets": ['no-peanuts'],
    "category": 'entree',
    "diningHall": 'Hampshire',
  },
  {
    "id": 6,
    "name": 'Pasta Primavera',
    "mealType": ['dinner'],
    "diets": ['vegetarian'],
    "category": 'entree',
    "diningHall": 'Hampshire',
  },
  {
    "id": 7,
    "name": 'Breakfast Burrito',
    "mealType": ['breakfast'],
    "diets": ['no-peanuts'],
    "category": 'entree',
    "diningHall": 'Hampshire',
  },
  {
    "id": 101,
    "name": 'Fruit Cup',
    "mealType": ['breakfast', 'lunch', 'dinner'],
    "diets": ['vegan', 'gluten-free', 'vegetarian', 'no-peanuts'],
    "category": 'snack',
    "diningHall": 'Hampshire',
  },
  {
    "id": 102,
    "name": 'Granola Bar',
    "mealType": ['breakfast', 'lunch'],
    "diets": ['vegetarian'],
    "category": 'snack',
    "diningHall": 'Hampshire',
  },
  {
    "id": 103,
    "name": 'Orange Juice',
    "mealType": ['breakfast'],
    "diets": ['vegan', 'gluten-free', 'vegetarian', 'no-peanuts'],
    "category": 'drink',
    "diningHall": 'Hampshire',
  },
  {
    "id": 104,
    "name": 'Iced Tea',
    "mealType": ['lunch', 'dinner'],
    "diets": ['vegan', 'gluten-free', 'vegetarian', 'no-peanuts'],
    "category": 'drink',
    "diningHall": 'Berkshire',
  },
  {
    "id": 105,
    "name": 'Yogurt Cup',
    "mealType": ['breakfast', 'lunch'],
    "diets": ['vegetarian', 'gluten-free'],
    "category": 'snack',
    "diningHall": 'Hampshire',
  },
  {
    "id": 106,
    "name": 'Trail Mix',
    "mealType": ['lunch', 'dinner'],
    "diets": ['vegetarian'],
    "category": 'snack',
    "diningHall": 'Hampshire',
  },
  {
    "id": 107,
    "name": 'Sparkling Water',
    "mealType": ['breakfast', 'lunch', 'dinner'],
    "diets": ['vegan', 'gluten-free', 'vegetarian', 'no-peanuts'],
    "category": 'drink',
    "diningHall": 'Hampshire',
  },
]